In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


df = pd.read_csv("Last_mile_delivery.csv")
df.head()

,timestamp,vehicle_gps_latitude,vehicle_gps_longitude,fuel_consumption_rate,eta_variation_hours,traffic_congestion_level,warehouse_inventory_level,loading_unloading_time,handling_equipment_availability,order_fulfillment_status,...,iot_temperature,cargo_condition_status,route_risk_level,customs_clearance_time,driver_behavior_score,fatigue_monitoring_score,disruption_likelihood_score,delay_probability,risk_classification,delivery_time_deviation
0,01-01-21 0:00,40.375568,-77.014318,5.136512,4.998009,5.927586,985.716862,4.951392,0.481294,0.761166,...,0.574400,0.777263,1.182116,0.502006,0.033843,0.978599,0.506152,0.885291,Moderate Risk,9.110682
1,01-01-21 1:00,33.507818,-117.036902,5.101512,0.984929,1.591992,396.700206,1.030379,0.620780,0.196594,...,-9.753493,0.091839,9.611988,0.966774,0.201725,0.918586,0.980784,0.544178,High Risk,8.175281
2,01-01-21 2:00,30.020640,-75.269224,5.090803,4.972665,8.787765,832.408935,4.220229,0.810933,0.152742,...,-6.491034,0.253529,6.570431,0.945627,0.264045,0.394215,0.998633,0.803322,High Risk,1.283594
3,01-01-21 3:00,36.649223,-70.190529,8.219558,3.095064,0.045257,0.573283,0.530186,0.008525,0.811885,...,-0.151276,0.877576,0.548952,4.674035,0.362885,0.905444,0.993320,0.025977,High Risk,9.304897
4,01-01-21 4:00,30.001279,-70.012195,5.000075,3.216077,8.004851,914.925067,3.620890,0.020083,0.053659,...,2.429448,0.262081,8.861443,3.445429,0.016957,0.258702,0.912433,0.991122,High Risk,7.752484

In [2]:
df.columns

Index(['timestamp', 'vehicle_gps_latitude', 'vehicle_gps_longitude',
       'fuel_consumption_rate', 'eta_variation_hours',
       'traffic_congestion_level', 'warehouse_inventory_level',
       'loading_unloading_time', 'handling_equipment_availability',
       'order_fulfillment_status', 'weather_condition_severity',
       'port_congestion_level', 'shipping_costs', 'supplier_reliability_score',
       'lead_time_days', 'historical_demand', 'iot_temperature',
       'cargo_condition_status', 'route_risk_level', 'customs_clearance_time',
       'driver_behavior_score', 'fatigue_monitoring_score',
       'disruption_likelihood_score', 'delay_probability',
       'risk_classification', 'delivery_time_deviation'],
      dtype='str')

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32065 entries, 0 to 32064
Data columns (total 26 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   timestamp                        32065 non-null  str
 1   vehicle_gps_latitude             32065 non-null  float64
 2   vehicle_gps_longitude            32065 non-null  float64
 3   fuel_consumption_rate            32065 non-null  float64
 4   eta_variation_hours              32065 non-null  float64
 5   traffic_congestion_level         32065 non-null  float64
 6   warehouse_inventory_level        32065 non-null  float64
 7   loading_unloading_time           32065 non-null  float64
 8   handling_equipment_availability  32065 non-null  float64
 9   order_fulfillment_status         32065 non-null  float64
 10  weather_condition_severity       32065 non-null  float64
 11  port_congestion_level            32065 non-null  float64
 12  shipping_costs                   32065 non-null  float64
 13  supplier_reliability_score       32065 non-null  float64
 14  lead_time_days                   32065 non-null  float64
 15  historical_demand                32065 non-null  float64
 16  iot_temperature                  32065 non-null  float64
 17  cargo_condition_status           32065 non-null  float64
 18  route_risk_level                 32065 non-null  float64
 19  customs_clearance_time           32065 non-null  float64
 20  driver_behavior_score            32065 non-null  float64
 21  fatigue_monitoring_score         32065 non-null  float64
 22  disruption_likelihood_score      32065 non-null  float64
 23  delay_probability                32065 non-null  float64
 24  risk_classification              32065 non-null  str
 25  delivery_time_deviation          32065 non-null  float64
dtypes: float64(24), str(2)
memory usage: 6.4 MB

In [4]:
df["failure"] = (df["delay_probability"] > 0.6).astype(int)

In [5]:
df["failure"].value_counts()

failure
1    21630
0    10435
Name: count, dtype: int64

In [7]:
features = [
    "traffic_congestion_level",
    "eta_variation_hours",
    "fuel_consumption_rate",
    "driver_behavior_score",
    "fatigue_monitoring_score",
    "disruption_likelihood_score",
    "weather_condition_severity",
    "supplier_reliability_score",
    "port_congestion_level",
    "loading_unloading_time",
    "handling_equipment_availability",
    "lead_time_days",
    "route_risk_level",
    "vehicle_gps_latitude",
    "vehicle_gps_longitude"
]

In [8]:
X = df[features]
y = df["failure"]

In [9]:
X.head()

,traffic_congestion_level,eta_variation_hours,fuel_consumption_rate,driver_behavior_score,fatigue_monitoring_score,disruption_likelihood_score,weather_condition_severity,supplier_reliability_score,port_congestion_level,loading_unloading_time,handling_equipment_availability,lead_time_days,route_risk_level,vehicle_gps_latitude,vehicle_gps_longitude
0,5.927586,4.998009,5.136512,0.033843,0.978599,0.506152,0.359066,0.986064,4.289160,4.951392,0.481294,2.128009,1.182116,40.375568,-77.014318
1,1.591992,0.984929,5.101512,0.201725,0.918586,0.980784,0.230660,0.463233,7.018373,1.030379,0.620780,12.608166,9.611988,33.507818,-117.036902
2,8.787765,4.972665,5.090803,0.264045,0.394215,0.998633,0.027210,0.598561,9.605064,4.220229,0.810933,14.124452,6.570431,30.020640,-75.269224
3,0.045257,3.095064,8.219558,0.362885,0.905444,0.993320,0.616619,0.742735,8.899616,0.530186,0.008525,3.818972,0.548952,36.649223,-70.190529
4,8.004851,3.216077,5.000075,0.016957,0.258702,0.912433,0.952385,0.431088,0.061760,3.620890,0.020083,14.001491,8.861443,30.001279,-70.012195

In [10]:
X.isnull().sum()

traffic_congestion_level           0
eta_variation_hours                0
fuel_consumption_rate              0
driver_behavior_score              0
fatigue_monitoring_score           0
disruption_likelihood_score        0
weather_condition_severity         0
supplier_reliability_score         0
port_congestion_level              0
loading_unloading_time             0
handling_equipment_availability    0
lead_time_days                     0
route_risk_level                   0
vehicle_gps_latitude               0
vehicle_gps_longitude              0
dtype: int64

In [11]:
X.dtypes

traffic_congestion_level           float64
eta_variation_hours                float64
fuel_consumption_rate              float64
driver_behavior_score              float64
fatigue_monitoring_score           float64
disruption_likelihood_score        float64
weather_condition_severity         float64
supplier_reliability_score         float64
port_congestion_level              float64
loading_unloading_time             float64
handling_equipment_availability    float64
lead_time_days                     float64
route_risk_level                   float64
vehicle_gps_latitude               float64
vehicle_gps_longitude              float64
dtype: object

In [12]:
y.value_counts()

failure
1    21630
0    10435
Name: count, dtype: int64

In [13]:
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

In [14]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [21]:
neg = (y == 0).sum()
pos = (y == 1).sum()

scale = neg / pos
print(scale)

0.48243180767452615

In [22]:
model = XGBClassifier(
    n_estimators=100,
    max_depth=5,
    learning_rate=0.1,
    scale_pos_weight=scale,
    random_state=42
)

In [23]:
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.5083424294401996
              precision    recall  f1-score   support

           0       0.31      0.44      0.36      2050
           1       0.67      0.54      0.60      4363

    accuracy                           0.51      6413
   macro avg       0.49      0.49      0.48      6413
weighted avg       0.56      0.51      0.52      6413

In [24]:
X_test.iloc[0]

traffic_congestion_level            5.523590
eta_variation_hours                 3.736822
fuel_consumption_rate              15.454229
driver_behavior_score               0.778853
fatigue_monitoring_score            0.964290
disruption_likelihood_score         0.554942
weather_condition_severity          0.462348
supplier_reliability_score          0.736213
port_congestion_level               9.751095
loading_unloading_time              1.690326
handling_equipment_availability     0.026702
lead_time_days                      1.233794
route_risk_level                    7.764165
vehicle_gps_latitude               47.504851
vehicle_gps_longitude             -74.847757
Name: 29063, dtype: float64

In [25]:
def explain(row):
    reasons = []

    # Traffic
    if row["traffic_congestion_level"] > 5:
        reasons.append("High traffic congestion")

    # ETA variation
    if row["eta_variation_hours"] > 2:
        reasons.append("Unstable ETA")

    # Fuel (proxy for inefficiency)
    if row["fuel_consumption_rate"] > 12:
        reasons.append("Inefficient route / high fuel usage")

    # Driver behavior
    if row["driver_behavior_score"] < 0.5:
        reasons.append("Poor driver behavior")

    # Fatigue
    if row["fatigue_monitoring_score"] > 0.8:
        reasons.append("Driver fatigue detected")

    # Disruption
    if row["disruption_likelihood_score"] > 0.5:
        reasons.append("High disruption likelihood")

    # Weather
    if row["weather_condition_severity"] > 0.5:
        reasons.append("Bad weather conditions")

    # Supplier
    if row["supplier_reliability_score"] < 0.6:
        reasons.append("Unreliable supplier")

    # Port congestion
    if row["port_congestion_level"] > 7:
        reasons.append("Port congestion")

    # Loading delay
    if row["loading_unloading_time"] > 1.5:
        reasons.append("Slow loading/unloading")

    # Equipment
    if row["handling_equipment_availability"] < 0.3:
        reasons.append("Low equipment availability")

    # Route risk
    if row["route_risk_level"] > 7:
        reasons.append("High route risk")

    return reasons

In [26]:
row = X_test.iloc[0]
explain(row)

['High traffic congestion',
 'Unstable ETA',
 'Inefficient route / high fuel usage',
 'Driver fatigue detected',
 'High disruption likelihood',
 'Port congestion',
 'Slow loading/unloading',
 'Low equipment availability',
 'High route risk']

In [29]:
def decision_engine(row, prob):

    reasons = explain(row)

    # High risk
    if prob > 0.7 or len(reasons) > 4:
        return "Call customer immediately + prioritize delivery"

    # Medium risk
    elif prob > 0.5 or len(reasons) > 2:
        return "Send WhatsApp/SMS reminder"

    # Specific conditions
    elif "Bad weather conditions" in reasons:
        return "Delay delivery due to weather"

    elif "High traffic congestion" in reasons:
        return "Re-route to avoid traffic"

    else:
        return "Proceed normally"

In [30]:
decision_engine(X_test.iloc[0], prob)

'Call customer immediately + prioritize delivery'

In [31]:
prob = float(model.predict_proba([X_test.iloc[0]])[:,1][0])

In [32]:
row = X_test.iloc[5]
prob = float(model.predict_proba([row])[:,1][0])

print(prob)
print(explain(row))
print(decision_engine(row, prob))

0.5612075328826904
['Unstable ETA', 'Poor driver behavior', 'High disruption likelihood', 'Bad weather conditions', 'Port congestion', 'Slow loading/unloading', 'Low equipment availability']
Call customer immediately + prioritize delivery

In [47]:
def contact_strategy(row, prob):

    reasons = explain(row)

    # Very high risk
    if prob > 0.75 and len(reasons) > 4:
        return "Call + SMS + WhatsApp"

    # High risk
    elif prob > 0.65 and len(reasons) > 3:
        return "WhatsApp + SMS"

    # Medium risk
    elif prob > 0.55:
        return "SMS reminder"

    # Low risk
    else:
        return "No contact needed"

In [48]:
contact_strategy(row, prob)

'SMS reminder'

In [57]:
df_test = X_test.copy()

df_test["failure_prob"] = model.predict_proba(X_test)[:,1]

# Decision
df_test["decision"] = [
    decision_engine(X_test.iloc[i], df_test["failure_prob"].iloc[i])
    for i in range(len(df_test))
]

# Contact
df_test["contact"] = [
    contact_strategy(X_test.iloc[i], df_test["failure_prob"].iloc[i])
    for i in range(len(df_test))
]

# Adjust function
def adjust(prob, decision, contact):

    if prob > 0.85:
        return prob - 0.18

    elif prob > 0.75:
        return prob - 0.12

    elif prob > 0.65:
        return prob - 0.08

    return prob

# Apply adjustment
df_test["adjusted_prob"] = [
    adjust(df_test["failure_prob"].iloc[i],
           df_test["decision"].iloc[i],
           df_test["contact"].iloc[i])
    for i in range(len(df_test))
]

# Compare
before = sum(df_test["failure_prob"] > 0.6)
after = sum(df_test["adjusted_prob"] > 0.6)

print("Before:", before)
print("After:", after)
print("Reduction:", before - after)

Before: 511
After: 423
Reduction: 88